### ISSUE TITLE
Destination directory not provided

### ISSUE THREAD

**Issue by leptest** [emphaticsunshine/grunt-specificity-graph#1]
Great work on creating a grunt plugin for this!

Though I've encountered an error with the destination directory and was hoping you could help.

![image](https://cloud.githubusercontent.com/assets/5265861/8849748/16b8a660-313a-11e5-9b81-7a9c0a2fb028.png)

![image](https://cloud.githubusercontent.com/assets/5265861/8849767/37b6b578-313a-11e5-83af-6fa1903393f3.png)

![image](https://cloud.githubusercontent.com/assets/5265861/8849700/c525899e-3139-11e5-8f4a-45fdb90ac179.png)

Should i provide more details to help troubleshoot this?

**Comment by emphaticsunshine** [comment]
Thanks @leptest for finding that out. I will look at that issue and update you on it.

**Comment by emphaticsunshine** [comment]
Sorry for such a delayed response @leptest but I wasn't able to reproduce this error. Can I your version of node and grunt?

**Comment by emphaticsunshine** [comment]
It should be fixed now.
