### ISSUE TITLE
The task doesn't create the HTML file

### ISSUE THREAD

**Issue by AurelioDeRosa** [emphaticsunshine/grunt-specificity-graph#5]
The task should create by default or via an option the possibility to create the HTML file showing the specificity graph. At the moment, it only creates the JSON file.

**Comment by emphaticsunshine** [comment]
Can you provide more details on it?

**Comment by emphaticsunshine** [comment]
Hey @AurelioDeRosa , I update my readme example. Update yours too. That files object need to be an array.

**Comment by AurelioDeRosa** [comment]
The new example works as expected. Thank you
